### obteter todos los empleados
GET http://localhost:4000/api/tipoEmpleado

### obteter un empleado
GET http://localhost:4000/api/tipoEmpleado/user-jperez-2024-1234-dsw

### crear un nuevo empleado
POST http://localhost:4000/api/tipoEmpleado
Content-Type: application/json

{
    "dni_empleado": "12345678",
    "nombre": "Juan",
    "apellido": "Pérez",
    "tel": "1122334455",
    "mail": "juan.perez@example.com",
    "domicilio": "Calle Falsa 123",
    "cuil": "20-12345678-3",
    "usuario": "juanp"
}


### modificar un empleado (PUT - recurso completo e idempotente)
PUT http://localhost:4000/api/tipoEmpleado/user-jperez-2024-1234-dsw
Content-Type: application/json

{
    "dni_empleado": "87654321",
    "nombre": "María",
    "apellido": "López",
    "tel": "5544332211",
    "mail": "maria.lopez@example.com",
    "domicilio": "Avenida Siempreviva 742",
    "usuario": "marial"
}

### modificar un atrubuto de un empleado 
PATCH http://localhost:4000/api/tipoEmpleado/user-jperez-2024-1234-dsw
Content-Type: application/json

{
    "tel": "6677889900",
    "domicilio": "Calle Nueva 789"
}

### borrar un tipo producto
DELETE http://localhost:4000/api/tipoEmpleado/user-jperez-2024-1234-dsw
