### obtener todos los tipo producto (público)
GET http://localhost:4000/api/tipoproducto

### obtener un tipo producto por su id
GET http://localhost:4000/api/tipoproducto/1

###obtener un tipo producto por su nombre

### 7. LOGIN ADMIN (Para obtener token)
POST http://localhost:4000/api/usuario/login
Content-Type: application/json

{
  "user_usuario": "admin1",
  "contraseña": "admin123"
}

### crear un nuevo tipo producto (Solo Admin)
POST http://localhost:4000/api/tipoproducto
Content-Type: application/json
Authorization: Bearer TOKEN_DE_ADMIN_AQUI

{
  "nombre_tipo": "Gabinetes"
}


### 4. ACTUALIZAR TIPO DE PRODUCTO COMPLETO (Solo Admin)
PUT http://localhost:4000/api/tipoproducto/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcl91c3VhcmlvIjoiYWRtaW4iLCJ0aXBvX3VzdWFyaW8iOjEsImlhdCI6MTc2MTQ1NTU4NywiZXhwIjoxNzYxNDU5MTg3fQ.z9TUGBxaxlxopuaOXA1quCpP5d9e_MssvoQLVPUaqvw

{
  "nombre_tipo": "Memorias", 
  "desc_tipo": "La memoria RAM (Random Access Memory) es un tipo de memoria volátil que se utiliza para almacenar datos e instrucciones de programas que la cpu necesita acceder rápidamente mientras el sistema está en funcionamiento."
}

### 5. ACTUALIZAR TIPO DE PRODUCTO PARCIAL (Solo Admin)
PATCH http://localhost:4000/api/tipoproducto/6
Content-Type: application/json
Authorization: Bearer TOKEN_DE_ADMIN_AQUI

{
  "desc_tipo": "Una unidad central de procesamiento, o CPU, es una pieza de hardware que permite que tu computadora interactúe con todas las aplicaciones y programas instalados." 
}

### 6. ELIMINAR TIPO DE PRODUCTO (Solo Admin)
DELETE http://localhost:4000/api/tipoproducto/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcl91c3VhcmlvIjoiYWRtaW4xIiwidGlwb191c3VhcmlvIjoxLCJpYXQiOjE3NjIxMzI1MTgsImV4cCI6MTc2MjEzNjExOH0.cuXxBJtNGmC_cxgFLhnAz8FOf3B2j-HhWfesMrSm6hU


### Probando manejo de errores

### CASO 2: Error - Nombre duplicado
POST http://localhost:4000/api/tipoproducto
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcl91c3VhcmlvIjoiYWRtaW4iLCJ0aXBvX3VzdWFyaW8iOjEsImlhdCI6MTc2MTQ1NTU4NywiZXhwIjoxNzYxNDU5MTg3fQ.z9TUGBxaxlxopuaOXA1quCpP5d9e_MssvoQLVPUaqvw

{
  "nombre_tipo": "Memorias"
}

### CASO 3: Error - Nombre vacío
POST http://localhost:4000/api/tipoproducto
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcl91c3VhcmlvIjoiYWRtaW4iLCJ0aXBvX3VzdWFyaW8iOjEsImlhdCI6MTc1OTUxNzg2OCwiZXhwIjoxNzU5NTIxNDY4fQ.kGMTqsAOi-4g0ZZ38UpCvp0YIjyfE0WAs1iFtVM7xj4

{
  "nombre_tipo": ""
}


### CASO 5: Error - Eliminar con productos asociados
DELETE http://localhost:4000/api/tipoproducto/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcl91c3VhcmlvIjoiYWRtaW4iLCJ0aXBvX3VzdWFyaW8iOjEsImlhdCI6MTc1OTUxNzg2OCwiZXhwIjoxNzU5NTIxNDY4fQ.kGMTqsAOi-4g0ZZ38UpCvp0YIjyfE0WAs1iFtVM7xj4

### CARGANDO TIPOS DE PRODUCTOS

POST http://localhost:4000/api/tipoproducto
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcl91c3VhcmlvIjoiYWRtaW4xIiwidGlwb191c3VhcmlvIjoxLCJpYXQiOjE3NjIxMzMxMDYsImV4cCI6MTc2MjEzNjcwNn0.wWhEYTXpO8iJv0XF_v0OQJ21brddUVtiDBYgYx65unM

{
  "nombre_tipo": "Gabinetes"
}

###
POST http://localhost:4000/api/tipoproducto
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcl91c3VhcmlvIjoiYWRtaW4xIiwidGlwb191c3VhcmlvIjoxLCJpYXQiOjE3NjIxMzMxMDYsImV4cCI6MTc2MjEzNjcwNn0.wWhEYTXpO8iJv0XF_v0OQJ21brddUVtiDBYgYx65unM

{
  "nombre_tipo": "Auriculares"
}

###


POST http://localhost:4000/api/tipoproducto
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcl91c3VhcmlvIjoiYWRtaW4xIiwidGlwb191c3VhcmlvIjoxLCJpYXQiOjE3NjIxMzMxMDYsImV4cCI6MTc2MjEzNjcwNn0.wWhEYTXpO8iJv0XF_v0OQJ21brddUVtiDBYgYx65unM

{
  "nombre_tipo": "Teclados"
}

###

POST http://localhost:4000/api/tipoproducto
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcl91c3VhcmlvIjoiYWRtaW4xIiwidGlwb191c3VhcmlvIjoxLCJpYXQiOjE3NjIxMzMxMDYsImV4cCI6MTc2MjEzNjcwNn0.wWhEYTXpO8iJv0XF_v0OQJ21brddUVtiDBYgYx65unM

{
  "nombre_tipo": "Mouses"
}

###

POST http://localhost:4000/api/tipoproducto
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcl91c3VhcmlvIjoiYWRtaW4xIiwidGlwb191c3VhcmlvIjoxLCJpYXQiOjE3NjIxMzMxMDYsImV4cCI6MTc2MjEzNjcwNn0.wWhEYTXpO8iJv0XF_v0OQJ21brddUVtiDBYgYx65unM

{
  "nombre_tipo": "Monitores"
}


###

POST http://localhost:4000/api/tipoproducto
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcl91c3VhcmlvIjoiYWRtaW4xIiwidGlwb191c3VhcmlvIjoxLCJpYXQiOjE3NjIxMzMxMDYsImV4cCI6MTc2MjEzNjcwNn0.wWhEYTXpO8iJv0XF_v0OQJ21brddUVtiDBYgYx65unM

{
  "nombre_tipo": "Procesadores"
}

###

POST http://localhost:4000/api/tipoproducto
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcl91c3VhcmlvIjoiYWRtaW4xIiwidGlwb191c3VhcmlvIjoxLCJpYXQiOjE3NjIxMzMxMDYsImV4cCI6MTc2MjEzNjcwNn0.wWhEYTXpO8iJv0XF_v0OQJ21brddUVtiDBYgYx65unM

{
  "nombre_tipo": "Accesorios"
}

###

POST http://localhost:4000/api/tipoproducto
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcl91c3VhcmlvIjoiYWRtaW4xIiwidGlwb191c3VhcmlvIjoxLCJpYXQiOjE3NjIxMzMxMDYsImV4cCI6MTc2MjEzNjcwNn0.wWhEYTXpO8iJv0XF_v0OQJ21brddUVtiDBYgYx65unM

{
  "nombre_tipo": "Almacenamiento"
}

